web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
  links:
    - mysql
  env_file:
    - '.env.web'
mysql:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  env_file:
    - '.env.db'
  labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
#  volumes:
#    - /mnt/swipe-rails:/var/lib/mysql
phpmyadmin:
  environment:
    PMA_HOST: mysql
    PMA_USER: root
    PMA_PASSWORD: "Testing"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_ne: sys=lb
  tty: true
  image: phpmyadmin/phpmyadmin:4.5.3.1-1
  ports:
    - "8080:8080"
  links:
  - 'mysql:mysql'
  stdin_open: true
elasticsearch:
  image: library/elasticsearch:2.2
  ports:
    - "9200:9200"
  labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
mariadb:
  image: library/mariadb:latest
  ports:
    - "23306:3306"
  env_file:
    - '.env.db'
  labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
memcached:
  image: library/memcached:latest
  ports:
    - "11211:11211"
  labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
